export default {
    FALIURE: 'FALIURE',
    ERROR: 'ERROR',
    SUCESS: 'SUCESS',
    INVALID_RESOURCE_ID: 'invalid resource id',
    NONE: 'none',
    DISCONNECTED: 'DISCONNECTED',
    FAILED: 'FAILED',
    READY: 'READY',
    RETRYING: 'RETRYING',
    FAILEDVERSION: 'FAILEDVERSION',
    NOTAVAILABLE: 'NOTAVAILABLE',
    TIMEDOUT: 'TIMEDOUT',
    UNABLE_TO_JOIN: 'Unable to join the meeting',
    DISPLAY_NAME_ERROR_MSG: 'Please enter valid alphanumeric characters at Display Name.',
    RESOURCE_ID_ERROR_MSG: 'Please enter valid alphanumeric characters at Resource ID.',
    HOST_NAME_ERROR_MSG: 'Please enter valid Host.',
    TOKEN_ERROR_MSG: 'Please enter valid Token.',
    VIDYO_CONNECTORDISCONNECTREASON_MiscError: 'Misc Error Occured',
    VIDYO_CONNECTORFAILREASON_MiscLocalError: 'Misc Local Error Occured',
    VIDYO_CONNECTORFAILREASON_MiscRemoteError: 'Misc Remote Error Occured',
    VIDYO_CONNECTORFAILREASON_InvalidToken: 'Invalid token',
    VIDYO_CONNECTORFAILREASON_ConnectionFailed: 'Connection Failed',
    VIDYO_CONNECTORFAILREASON_ConnectionLost: 'Connection Lost',
    VIDYO_CONNECTORFAILREASON_ConnectionTimeout: 'Connection Timeout',
    VIDYO_CONNECTORFAILREASON_NoResponse: 'No Response',
    VIDYO_CONNECTORFAILREASON_Terminated: 'Connection Terminate',
    VIDYO_CONNECTORFAILREASON_UnableToCreateResource: 'Unable to create the resource',
    VIDYO_CONNECTORFAILREASON_NoResponseFromResource: 'No response from resource',
    VIDYO_CONNECTORFAILREASON_InvalidResourceId: 'Invalid Resource ID',
    VIDYO_CONNECTORFAILREASON_ResourceFull: 'Resource Full',
    VIDYO_CONNECTORFAILREASON_NotMember: 'Not A Member',
    VIDYO_CONNECTORFAILREASON_Banned: 'Member Is Banned',
    VIDYO_CONNECTORFAILREASON_MediaNotEnabled: 'Media Is Not Enabled',
    VIDYO_CONNECTORFAILREASON_MediaFailed: 'Media Failed',
    VIDYO_CONNECTORFAILREASON_MiscError: 'Misc Error',
    VIDYO_CONNECTORFAILREASON_InvalidDisplayNameLength: 'Invalid Display name',
    VIDYO_CONNECTORDISCONNECTREASON_Disconnected: 'Disconnected',
    VIDYO_CONNECTORDISCONNECTREASON_ConnectionLost: 'Connection Lost',
    VIDYO_CONNECTORDISCONNECTREASON_ConnectionTimeout: 'Connection Timeout',
    VIDYO_CONNECTORDISCONNECTREASON_NoResponse: 'No Response',
    VIDYO_CONNECTORDISCONNECTREASON_Terminated: 'Connection Terminate',
    VIDYO_CONNECTORDISCONNECTREASON_MiscLocalError: 'Misc Local Error Occured',
    VIDYO_CONNECTORDISCONNECTREASON_MiscRemoteError: 'Misc Remote Error Occured'
};
